# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Lab9' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'lab9' do
    @driver.get('http://localhost:3000/calc/input')
    @driver.find_element(:id, 'less_than_number').click
    @driver.find_element(:id, 'less_than_number').send_keys('1000')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, 'tbody:nth-child(2) td:nth-child(1)').text).to eq('1')
    expect(@driver.find_element(:css, 'tbody:nth-child(3) td:nth-child(1)').text).to eq('2')
    expect(@driver.find_element(:css, 'tbody:nth-child(4) td:nth-child(1)').text).to eq('3')
    expect(@driver.find_element(:css, 'tbody:nth-child(5) td:nth-child(1)').text).to eq('11')
    expect(@driver.find_element(:css, 'tbody:nth-child(6) td:nth-child(1)').text).to eq('22')
    expect(@driver.find_element(:css, 'tbody:nth-child(7) td:nth-child(1)').text).to eq('26')
    expect(@driver.find_element(:css, 'tbody:nth-child(8) td:nth-child(1)').text).to eq('101')
    expect(@driver.find_element(:css, 'tbody:nth-child(9) td:nth-child(1)').text).to eq('111')
    expect(@driver.find_element(:css, 'tbody:nth-child(10) td:nth-child(1)').text).to eq('121')
    expect(@driver.find_element(:css, 'tbody:nth-child(11) td:nth-child(1)').text).to eq('202')
    expect(@driver.find_element(:css, 'tbody:nth-child(12) td:nth-child(1)').text).to eq('212')
    expect(@driver.find_element(:css, 'tbody:nth-child(13) td:nth-child(1)').text).to eq('264')
    expect(@driver.find_element(:css, 'tbody:nth-child(14) td:nth-child(1)').text).to eq('307')
    expect(@driver.find_element(:css, 'tbody:nth-child(15) td:nth-child(1)').text).to eq('836')
    expect(@driver.find_element(:css, 'tbody:nth-child(16) th:nth-child(1)').text).to eq('Количество элементов:')
    expect(@driver.find_element(:css, 'tbody:nth-child(16) th:nth-child(2)').text).to eq('14')
  end
end
